ASPNET_CoreSessionApps/Controllers/FinalBIllController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using ASPNET_CoreSessionApps.Services;
using ASPNET_CoreSessionApps.Models;
using ASPNET_CoreSessionApps.SessionExtensions;


namespace ASPNET_CoreSessionApps.Controllers
{
    public class FinalBillController : Controller
    {
        IBill finalBill;
        
        public FinalBillController(IBill fb)
        {
            finalBill = fb;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            var selProducts = HttpContext.Session.GetSessionData<List<BillDetails>>("PurchasedProduct");

            var billMaster = new BillMaster();
            //Calculate the Total Bill Amount
            foreach (var item in selProducts)
            {
                billMaster.BillAmount += item.RowPrice;
            }

             billMaster.BillDetails = selProducts;

            finalBill.GenerateBill(billMaster, billMaster.BillDetails.ToArray());

            return View(billMaster);
        }

         
    }
}

ASPNET_CoreSessionApps/Views/FinalBill/Index.cshtml
@model ASPNET_CoreSessionApps.Models.BillMaster

<h1> The Final Bill</h1>
<form id="frmFinal" asp-controller="FinalBill" role="form">
    <table class="table table-bordered table-condensed table-striped">
        <thead>
            <tr>
                <td  colspan="2">
                    Bill No
                </td>
                <td>
                    <input type="text" asp-for="@Model.BillNo" class="form-control"/>
                </td>
            </tr>
            <tr>
                <td>Product Name</td>
                <td>Quantity</td>
                <td>Row Price</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.BillDetails)
            {
                <tr>
                    <td>@item.ProductName</td>
                    <td>@item.Quantity</td>
                    <td>@item.RowPrice</td>
            </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="2">
                    Total Bill
                </td>
                <td>
                    <input type="text" asp-for="@Model.BillAmount" class="form-control" readonly/>
                </td>
            </tr>
        </tfoot>
    </table>
</form>