ASPNET_CoreSessionApps/Controllers/BillGeneratorController.cs
using ASPNET_CoreSessionApps.Models;
using ASPNET_CoreSessionApps.SessionExtensions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
namespace ASPNET_CoreSessionApps.Controllers
{
    public class BillGeneratorController : Controller
    {
        List<BillDetails> selProducts;

        public BillGeneratorController()
        {
            selProducts = new List<BillDetails>();
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            ViewBag.UnitPrice = HttpContext.Session.GetInt32("UnitPrice");
            var billDetails = HttpContext.Session.GetSessionData<BillDetails>("SelProduct");
            if (billDetails != null)
            {
                selProducts = HttpContext.Session.GetSessionData<List<BillDetails>>("PurchasedProduct");
            }
            return View(billDetails);
        }

        [HttpPost]
        public IActionResult Index(BillDetails b, string purchase)
        {
            if (purchase == "Save and Continue Purchase")
            {
                //Check if the session contains List of purchased prducts
                selProducts = HttpContext.Session.GetSessionData<List<BillDetails>>("PurchasedProduct");
                if (selProducts == null)
                {
                    selProducts = new List<Models.BillDetails>();
                }

                //Save the selected product in Session
                selProducts.Add(b);
                HttpContext.Session.SetSessionData<List<BillDetails>>("PurchasedProduct", selProducts);
                //Go to the ProductMVC     
                return RedirectToAction("Index", "Product");
            }
            else if(purchase == "Save and CheckOut")
            {
                selProducts = HttpContext.Session.GetSessionData<List<BillDetails>>("PurchasedProduct");
                if (selProducts == null)
                {
                    selProducts = new List<Models.BillDetails>();
                }
                var selBill = HttpContext.Session.GetSessionData<BillDetails>("SelProduct");
                ViewBag.UnitPrice = HttpContext.Session.GetInt32("UnitPrice");
                selBill.Quantity = b.Quantity;
                selBill.RowPrice = b.RowPrice;
                selProducts.Add(selBill);
                HttpContext.Session.SetSessionData<List<BillDetails>>("PurchasedProduct", selProducts);
                return RedirectToAction("Index", "FinalBill");
            }
            return View();
        }
    }
}

ASPNET_CoreSessionApps/Views/BillGenerator/Index.cshtml
@model ASPNET_CoreSessionApps.Models.BillDetails



<form asp-controller="BillGenerator"  role="form" id="frmbill">
    <table class="table table-striped table-bordered table-condensed">
        <tr>
            <td>
                Product Id:
            </td>
            <td>
                <input type="text" asp-for="ProductId" readonly class="form-control"/>
            </td>
        </tr>
        <tr>
            <td>
                Product Name:
            </td>
            <td>
                <input type="text" asp-for="ProductName" readonly class="form-control"/>
                <span>Unit Price : @ViewBag.UnitPrice</span>
            </td>
        </tr>
        <tr>
            <td>
                Quantity:
            </td>
            <td>
                <input type="text" asp-for="Quantity" class="form-control"
                        />
            </td>
        </tr>
        <tr>
            <td>
                Price:
            </td>
            <td>
                <input type="text" asp-for="RowPrice" class="form-control"/>
            </td>
        </tr>
        <tr>
            <td>
                <input type="submit" name="purchase"
                       value="Save and Continue Purchase" 
                       class="btn btn-link"/>
            </td>
            <td>
                <input type="submit" name="purchase"
                       value="Save and CheckOut"
                       class="btn btn-link" />
            </td>
        </tr>
    </table>
</form>

<script src="~/lib/jquery/dist/jquery.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#Quantity").on('change', function () {
            $("#RowPrice").val($(this).val() * @ViewBag.UnitPrice);
        });
    });
</script>